name: Release

on:
  workflow_dispatch:
    inputs:
      publish_beta:
        description: 'Publish as beta'
        required: false
        default: 'false'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Package and Publish'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: >
          ./PackAndPublish
          -Publish
          -Beta:$${{ github.event.inputs.publish_beta }}
        shell: pwsh
        working-directory: ./scripts
